services:
  postgres:
    image: postgres:17-alpine
    container_name: unsaid-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      postgres 
      -c max_connections=200 
      -c shared_buffers=256MB 
      -c effective_cache_size=768MB 
      -c work_mem=8MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 2G
    networks:
      - unsaid-network

  backend:
    build: .
    image: unsaid-backend:latest
    container_name: unsaid-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          cpus: '4.0'
#          memory: 4G
    ports:
      - "8080:8080"
    networks:
      - unsaid-network
  worker:
    image: unsaid-backend:latest # Dùng lại image vừa build ở trên
    container_name: unsaid-worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=worker # Kích hoạt profile Worker
      - SERVER_PORT=0 # Tắt web server (hoặc chạy random port) để tiết kiệm resource
    depends_on:
      backend: # Đảm bảo backend build xong thì worker mới chạy
        condition: service_started
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
#    deploy:
#      resources:
#        limits:
#          cpus: '2.0'
#          memory: 2G
    networks:
      - unsaid-network
  redis:
    image: redis:alpine
    container_name: unsaid-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./volumes/redis/data:/data
    networks:
      - unsaid-network

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: unsaid-rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # UI
    environment:
      RABBITMQ_DEFAULT_USER: unsaid
      RABBITMQ_DEFAULT_PASS: unsaid
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_log:/var/log/rabbitmq
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - unsaid-network

networks:
  unsaid-network:
    driver: bridge